# Build for Linux, macOS and MinGW. On MSVC use build.bat instead.
#
#   make            build the tool
#   make test       build and run the test suite (offline tiers)
#   make test-online / make test-full   include the network tiers
#   make gui        build the graphical front-end

CC      ?= cc
CXX     ?= c++
CFLAGS  ?= -std=c99 -O2 -Wall -Wextra -pedantic
CPPFLAGS += -D_POSIX_C_SOURCE=200809L -D_DEFAULT_SOURCE -D_DARWIN_C_SOURCE

SRCDIR  := src
TESTDIR := test
GUIDIR  := gui
OBJDIR  := build
TESTOBJ := $(OBJDIR)/test
GUIOBJ  := $(OBJDIR)/gui

# Everything except the CLI entry point, so the tests can link the same code.
LIBSRC  := $(filter-out $(SRCDIR)/main.c,$(wildcard $(SRCDIR)/*.c))
LIBOBJ  := $(patsubst $(SRCDIR)/%.c,$(OBJDIR)/%.o,$(LIBSRC))
MAINOBJ := $(OBJDIR)/main.o
TESTSRC := $(wildcard $(TESTDIR)/*.c)
TESTOBJS := $(patsubst $(TESTDIR)/%.c,$(TESTOBJ)/%.o,$(TESTSRC))

TARGET      := $(OBJDIR)/tabber
TESTTARGET  := $(TESTOBJ)/test_tabber
GUITARGET   := $(OBJDIR)/tabber-gui

UNAME_S := $(shell uname -s)

# HTTP comes from WinHTTP on Windows and from libcurl everywhere else.
ifeq ($(OS),Windows_NT)
  TARGET := $(OBJDIR)/tabber.exe
  TESTTARGET := $(TESTOBJ)/test_tabber.exe
  GUITARGET := $(OBJDIR)/tabber-gui.exe
  LDLIBS += -ladvapi32 -lole32 -lshell32 -luuid -lwinhttp -lws2_32
else
  LDLIBS += -lcurl
endif

all: $(TARGET)

$(TARGET): $(MAINOBJ) $(LIBOBJ)
	$(CC) $(CFLAGS) -o $@ $^ $(LDLIBS)

# The fresh savefile is built into the binary (src/resource_save.c), so the
# executable is the whole program: nothing has to ship beside it.

$(OBJDIR)/%.o: $(SRCDIR)/%.c | $(OBJDIR)
	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $<

$(TESTOBJ)/%.o: $(TESTDIR)/%.c | $(TESTOBJ)
	$(CC) $(CFLAGS) $(CPPFLAGS) -I$(SRCDIR) -c -o $@ $<

$(TESTTARGET): $(TESTOBJS) $(LIBOBJ)
	$(CC) $(CFLAGS) -o $@ $^ $(LDLIBS)

$(OBJDIR) $(TESTOBJ) $(GUIOBJ):
	mkdir -p $@

test: $(TESTTARGET)
	$(TESTTARGET)

test-online: $(TESTTARGET)
	$(TESTTARGET) --online

test-full: $(TESTTARGET)
	$(TESTTARGET) --full

# ---- The graphical front-end -------------------------------------------------
# Dear ImGui and GLFW are built from their sources under vendor/, not linked
# against a prebuilt library: a .lib or .a is per-compiler and per-architecture,
# and this tree already has three operating systems to keep happy. GLFW picks
# its window backend from a define, one per platform.

IMGUIDIR := vendor/imgui
GLFWDIR  := vendor/glfw

IMGUISRC := imgui.cpp imgui_draw.cpp imgui_tables.cpp imgui_widgets.cpp \
            imgui_demo.cpp
IMGUISRC += backends/imgui_impl_glfw.cpp backends/imgui_impl_opengl3.cpp

# Shared by every backend, the do-nothing one included.
GLFWSRC := context.c init.c input.c monitor.c platform.c vulkan.c window.c \
           egl_context.c osmesa_context.c \
           null_init.c null_monitor.c null_window.c null_joystick.c

ifeq ($(OS),Windows_NT)
  GLFWSRC += win32_init.c win32_joystick.c win32_module.c win32_monitor.c \
             win32_thread.c win32_time.c win32_window.c wgl_context.c
  GUIDEFS := -D_GLFW_WIN32 -DUNICODE -D_UNICODE
  GUILIBS := -lopengl32 -lgdi32 -lshell32 -luser32
  # -mwindows: a windowed program, so no console is opened alongside it.
  GUILINK := -mwindows
else ifeq ($(UNAME_S),Darwin)
  GLFWSRC += cocoa_init.m cocoa_joystick.m cocoa_monitor.m cocoa_window.m \
             nsgl_context.m macos_time.c posix_module.c posix_thread.c
  GUIDEFS := -D_GLFW_COCOA
  GUILIBS := -framework Cocoa -framework IOKit -framework QuartzCore \
             -framework OpenGL
else
  # X11 only. Wayland would also need its protocol headers generated by
  # wayland-scanner at build time, which is more than this Makefile should
  # know; under a Wayland session XWayland runs the window all the same.
  GLFWSRC += x11_init.c x11_monitor.c x11_window.c xkb_unicode.c glx_context.c \
             posix_module.c posix_time.c posix_thread.c posix_poll.c
  ifeq ($(UNAME_S),Linux)
    GLFWSRC += linux_joystick.c
  endif
  GUIDEFS := -D_GLFW_X11
  GUILIBS := -lGL -lX11 -lpthread -ldl -lm
endif

GUIINC   := -I$(SRCDIR) -I$(IMGUIDIR) -I$(IMGUIDIR)/backends -I$(GLFWDIR)/include
# The backend files sit a directory down, but every object lands in one place;
# no two of these share a basename, and none of them clashes with the tool's.
GUIOBJS  := $(addprefix $(GUIOBJ)/,$(notdir $(IMGUISRC:.cpp=.o)))
GUIOBJS  += $(addprefix $(GUIOBJ)/,$(patsubst %.c,%.o,$(patsubst %.m,%.o,$(GLFWSRC))))
GUIOBJS  += $(GUIOBJ)/main.o

# Vendored code is compiled without the project's warning flags: its warnings
# are upstream's to fix, and they would bury ours. Our own GUI code keeps them.
VENDORCFLAGS   := -std=c99 -O2 $(GUIDEFS) $(GUIINC)
VENDORCXXFLAGS := -std=c++11 -O2 $(GUIINC)

gui: $(GUITARGET)

# The tool's own objects go in too: the GUI is a second front-end onto the same
# library, not a second copy of it. They sit in $(OBJDIR) while the GUI's sit in
# $(GUIOBJ), which is what keeps our platform.o apart from GLFW's.
$(GUITARGET): $(GUIOBJS) $(LIBOBJ)
	$(CXX) -o $@ $^ $(GUILIBS) $(GUILINK) $(LDLIBS)

$(GUIOBJ)/main.o: $(GUIDIR)/main.cpp | $(GUIOBJ)
	$(CXX) $(VENDORCXXFLAGS) -Wall -Wextra -c -o $@ $<

$(GUIOBJ)/%.o: $(IMGUIDIR)/%.cpp | $(GUIOBJ)
	$(CXX) $(VENDORCXXFLAGS) -c -o $@ $<

$(GUIOBJ)/%.o: $(IMGUIDIR)/backends/%.cpp | $(GUIOBJ)
	$(CXX) $(VENDORCXXFLAGS) -c -o $@ $<

$(GUIOBJ)/%.o: $(GLFWDIR)/src/%.c | $(GUIOBJ)
	$(CC) $(VENDORCFLAGS) $(CPPFLAGS) -c -o $@ $<

$(GUIOBJ)/%.o: $(GLFWDIR)/src/%.m | $(GUIOBJ)
	$(CC) $(VENDORCFLAGS) $(CPPFLAGS) -c -o $@ $<

clean:
	rm -rf $(OBJDIR)

.PHONY: all test test-online test-full gui clean
