/*
 * resource.h - Files that ship inside the executable.
 *
 * tabber is distributed as a single binary, so the one file it used to carry
 * beside itself — the fresh savefile handed to a tab that has never been
 * played — is embedded instead (see resource_save.c, which is generated by
 * tools/embed_resource.py). A copy on disk still wins when there is one, so a
 * portable install can override it without a rebuild; see save_fresh_path.
 */
#ifndef TABBER_RESOURCE_H
#define TABBER_RESOURCE_H

#include <stddef.h>

/* nprofile.zip: a ZIP holding one pristine savefile. */
extern const unsigned char RES_FRESH_SAVE[];
extern const size_t RES_FRESH_SAVE_LEN;

#endif /* TABBER_RESOURCE_H */
